### ISSUE TITLE
Receive traceback KeyError: 'RECORD_ID'

### ISSUE THREAD

**Issue by h1ghbr0w** [luisnabais/docker-cloudflare-ddns#1]
Nice work on Cloudflare DDNS updater.  I've been trying to get a working script, and this looks like it meets the needs.

On first run (excluding RECORD_ID):

`./update_ddns.py     --email [redacted]     --api-key [redacted]   --hostname [redacted]    --zone-id [redacted zone_id]  --ttl 600`

`[2022-05-19 14:42:48] Getting current Public IP Address...
[2022-05-19 14:42:49] Public IP address [redacted]
Traceback (most recent call last):
  File "/home/chris/./update_ddns.py", line 53, in <module>
    if not os.environ['RECORD_ID']:
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'RECORD_ID
`

Also tried with RECORD_ID passed (guessed) receive
`./update_ddns.py     --email [redacted]     --api-key [redacted]   --hostname [redacted]    --zone-id [redacted zone_id]  --record_id [redacted record_id] --ttl 600`

`Traceback (most recent call last):
  File "/home/chris/./update_ddns.py", line 53, in <module>
    if not os.environ['RECORD_ID']:
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'RECORD_ID'
`

I couldnt find specific mention of RECORD_ID via Cloudflare DNS site, tried using 'ACCOUNT_ID' but this no doubt is wrong....  your directions are clear in that RECORD_IDs are returned, but I cannot get that far.

Any further direction would be much appreciated.

Thanks Chris

**Comment by luisnabais** [comment]
Hello Chris.

Sorry for the issue you found.
I just fixed the code and rebuilt the Docker containers.

I didn't do the correct validation for the RECORD_ID environment variable and I forgot to update the README.md file with the correct syntax for environment variables support, before I used arguments, but then I opted for environment variables for better Docker integration.

Now it should be working correctly. Please pull the latest code from the repository and test again. I would appreciate if you give me feedback afterward.

Thank you.
Best regards,
Luís Nabais

**Comment by h1ghbr0w** [comment]
Hi Luis, very nice work, I ran ./upgrade_ddns.py direct after first running without RECORD_ID, found id then set RECORD_ID, then ran perfectly. 

Thanks so much, this is awesome!  I've got to learn Python!

**Comment by luisnabais** [comment]
Than you for your feedback, Chris.

I'm glad I could help!
